USE SuperheroesDb

CREATE TABLE Superhero (
SuperheroId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(50) IS NOT NULL,
Alias NVARCHAR(50),
Origin NVARCHAR(50)
)

CREATE TABLE Assistant (
AssistantId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(50) IS NOT NULL
)

CREATE TABLE Power (
PowerId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(50) IS NOT NULL,
Description NVARCHAR(50),
)

